name: ESPHome Compatibility Monthly
"on":
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  full-matrix:
    name: Run Full Matrix
    uses: ./.github/workflows/esphome-compatibility.yml
    with:
      run_mode: full
